### ISSUE TITLE
在使用急用版教程的参数的时候，发现可能需要给pipe中的x265设置“--input -”才能正常工作

### ISSUE THREAD

**Issue by Ronifue** [iAvoe/x264-x265-copypaste-tutorial-with-obs-record-setting#1]
![4063a6c742cbbe0d199ed38030fe78fa](https://github.com/user-attachments/assets/4fa7e378-1018-4b19-8c2c-9a5b577a211b)

这是我在使用《急用版x265教程 v33.3 by Avoe.pdf》的(ffmpeg pipe) x265 CLI 命令的时候出现的问题

将命令中"--y4m - --output"中的"-"删除，并替换为"--input -"，问题解决

可能是因为使用了改版的x265，从而被要求强制用input，以下是我使用过，并出现了报错的两个版本：
https://github.com/jpsdr/x265/releases/tag/4.00.004
https://github.com/Patman86/x265-Mod-by-Patman/releases/tag/3.6%2B85%2B1

我相信用改版的x265的人有很多，鉴于此修改一下教程中的参数可以提高教程的通用性
![c743ecec751071f3e7d2b6f2e7b6e533](https://github.com/user-attachments/assets/e58a57bf-9c4c-4dc0-97ab-bf92655f892f)

**Comment by iAvoe** [comment]
需要进一步测试

**Comment by iAvoe** [comment]
已复现并修复：[62e3c63](https://github.com/iAvoe/x264-x265-copypaste-tutorial-with-obs-record-setting/commit/62e3c63e20168e61aafe312687ed990cff2bb9d8)
